//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherInformationAcquisition.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeatherInformationAcquisition.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 城市代码	城市名称
        ///54511	北京
        ///54499	昌平
        ///54433	朝阳
        ///54594	大兴
        ///54596	房山
        ///54514	丰台
        ///54399	海淀
        ///54419	怀柔
        ///54505	门头沟
        ///54416	密云
        ///54424	平谷
        ///54513	石景山
        ///54398	顺义
        ///54431	通州
        ///54406	延庆
        ///54517	天津
        ///54525	宝坻
        ///54528	北辰
        ///54623	滨海新区
        ///54645	大港
        ///54526	东丽
        ///54530	汉沽
        ///54428	蓟州
        ///54622	津南
        ///54619	静海
        ///54529	宁河
        ///54523	武清
        ///54527	西青
        ///53698	石家庄
        ///54602	保定
        ///54616	沧州
        ///54423	承德
        ///53892	邯郸
        ///54702	衡水
        ///54515	廊坊
        ///54449	秦皇岛
        ///54610	任丘
        ///54503	容城
        ///54534	唐山
        ///53798	邢台
        ///54401	张家口
        ///54604	安国
        ///54609	安平
        ///54605	安新
        ///54518	霸州
        ///53785	柏乡
        ///54618	泊头
        ///54535	曹妃甸
        ///54538	曹妃甸工业区        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string cities {
            get {
                return ResourceManager.GetString("cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 城市id	城市名称
        ///2	北京市
        ///3	北京市朝阳区
        ///4	北京市通州区
        ///5	昌平区
        ///6	顺义区
        ///7	怀柔区
        ///8	大兴区
        ///9	平谷区
        ///10	密云区
        ///11	延庆区
        ///12	丰台区
        ///13	石景山区
        ///14	房山区
        ///15	门头沟区
        ///16	八达岭
        ///17	佛爷顶
        ///18	汤河口
        ///20	斋堂
        ///21	霞云岭
        ///22	海淀区
        ///24	天津市
        ///25	宝坻区
        ///26	武清区
        ///27	宁河区
        ///28	静海区
        ///29	蓟州区
        ///30	东丽区
        ///31	西青区
        ///32	北辰区
        ///33	汉沽
        ///34	津南区
        ///35	塘沽
        ///36	大港
        ///37	滨海新区
        ///39	上海市
        ///40	嘉定区
        ///41	浦东新区
        ///42	金山区
        ///43	松江区
        ///44	青浦区
        ///45	南汇
        ///46	奉贤区
        ///47	崇明区
        ///48	上海市宝山区
        ///49	徐汇区
        ///50	闵行区
        ///52	重庆市
        ///53	黔江区
        ///54	北碚区
        ///57	巴南区
        ///59	长寿区
        ///60	合川区
        ///61	永川区
        ///62	江津区
        ///63	南川区
        ///64	綦江区
        ///65	潼南区
        ///66	铜梁区
        ///67	大足区
        ///68	荣昌区
        ///69	璧山区
        ///70	垫江县
        ///71	武隆区
        ///72	丰都县
        ///73	城口县
        ///74	梁平区
        ///75	开州区
        ///76	巫溪县
        ///77	巫山县
        ///78	奉节县
        ///79	云阳县
        ///80	忠县 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string 城市ID列表 {
            get {
                return ResourceManager.GetString("城市ID列表", resourceCulture);
            }
        }
    }
}
